name: Actions Workflow

on: 
  # schedule:
  #   - cron: "0/5 * * * *"

  # repository_dispatch:
  #   types: [build]

  push:
    branches:
      - master
  pull_request:
    # branches to ignore (run on all except. We can't have branches and branches-ignore at same time)
    # branches-ignore:
    branches:
      - master
      # help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - 'feature/*' #matches feature/featA, feature/featB Doesn't match feature/feat/a
      - 'feature/**' #matches feature/feat/a, feature/featA and feature/featB
      - '!feature/featC' #will ignore this branch even though it passes the criteria above. This is b/c of the exclamation mark
    # activity types for the pull-request
    types: [closed, assigned, opened, reopened]
    ##tags and tags-ignore can't be together just like branches and branches-ignore
    #tags:
    #  - v1.*
    #tags-ignore:
    #paths
    #paths:
    #  - '**.js'
    #  - '!folder/filename.js'
    #paths-ignore:
    #  - 'docs/**'

jobs:
  # A job
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      # A step. An action.
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        # Providing an input
        with:
          who-to-greet: Henrietha
      # End of the action

      # A step. An action. Echooing the output the output
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"c