name: Action Workflow

on: [push]

jobs:
  # A job
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      # A step. An action
      - name: Simple JS Actions
        id: greet
        uses: areathy/cooking-technique@master
        # Providing an input
        with:
          who-to-greet: Henrietha Chidiebere
      # End of the action

      # A step. An action. Echooing the output the output
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"